import $ from "jquery";

import "./components/brushdesigner.v1/jqbrushdesigner.css";
import "./components/bigColorPicker/bigColorPicker.css";
import "./components/paintBoard/paintBoard.css";
import "./components/paintTools/paintTools.css";
import "./components/simpleColorPicker/simpleColorPicker.css";
import "./components/simpleLineWidthPicker/simpleLineWidthPicker.css";
import "./components/windowsManager/windowsManager.css";
import "./components/newDocumentDialog/newDocumentDialog.css";
import "./components/retroBrushDesigner/retroBrushDesigner.css";
import "./components/patternsView/patternsView.css";
import "./components/gradientPanel/gradientPanel.css";
import "./components/starGenerator/starGenerator.css";
import "./components/coordinateLabel/coordinateLabel.css";
import "../vendor/ajsr-confirm/dist/css/tmplt-default.css";
import "../vendor/ajsr-notify/dist/css/tmplt-default.css";
import "./toolsBar.css";

window.$ = $;
window.jQuery = $;

await import("./components/brushdesigner.v1/jqbrushdesigner.js");
await import("./components/brushdesigner.v1/brushEditorOutputs.js");
await import("./components/bigColorPicker/bigColorPicker.js");
await import("../vendor/div-lines/dist/div-lines.min.js");
await import("./components/coordinateLabel/coordinateLabel.js");
await import("./components/paintBoard/tempLayer.js");
await import("./components/paintBoard/paintBoard.js");
await import("./components/paintTools/paintTools.js");
await import("./components/simpleColorPicker/simpleColorPicker.js");
await import("./components/simpleLineWidthPicker/simpleLineWidthPicker.js");
await import("./components/windowsManager/windowsManager.js");
await import("./components/newDocumentDialog/newDocumentDialog.js");
await import("./components/retroBrushDesigner/retroBrushDesigner.js");
await import("./components/patternsView/patternsView.js");
await import("./components/gradientPanel/gradientPanel.js");
await import("./components/starGenerator/starGenerator.js");
await import("./components/brushdesigner.v2/brushdesigner.v2.js");
await import("../vendor/ajsr-confirm/dist/ajsr-js-confirm.min.js");
await import("../vendor/ajsr-notify/dist/ajsr-notify.min.js");
await import("./app.clipboard.js");
await import("./app.openWindows.js");
await import("./app.js");
await import("./zoom.js");
