import $ from "jquery";
import brushDesigner2BackgroundUrl from "./components/brushdesigner.v2/bd2-bg.png";
import brushDesigner2HandlesUrl from "./components/brushdesigner.v2/bd2-handles.png";
import resizeImageResamplingAlgorithms from "./components/resizeImage/resamplingAlgorithms.json";

import "./components/brushdesigner.v1/jqbrushdesigner.css";
import "./components/brushdesigner.v2/brushdesigner.v2.css";
import "./components/bigColorPicker/bigColorPicker.css";
import "./components/appMenu/appMenu.css";
import "./components/layersPanel/layersPanel.css";
import "./components/foregroundBackgroundColors/foregroundBackgroundColors.css";
import "./components/paintBoard/paintBoard.css";
import "./components/boardRules/boardRules.css";
import "./components/paintTools/paintTools.css";
import "./components/simpleColorPicker/simpleColorPicker.css";
import "./components/simpleLineWidthPicker/simpleLineWidthPicker.css";
import "./components/simpleBrushWidthPicker/simpleBrushWidthPicker.css";
import "./components/windowsManager/windowsManager.css";
import "./components/modalWindow/modalWindow.css";
import "./components/newDocumentDialog/newDocumentDialog.css";
import "./components/resizeImage/resizeImage.css";
import "./components/brightnessContrastDialog/brightnessContrastDialog.css";
import "./components/multiPaste/multiPaste.css";
import "./components/retroBrushDesigner/retroBrushDesigner.css";
import "./components/randomLinesDesigner/randomLinesDesigner.css";
import "./components/patternsView/patternsView.css";
import "./components/gradientPanel/gradientPanel.css";
import "./components/starGenerator/starGenerator.css";
import "./components/coordinateLabel/coordinateLabel.css";
import "./components/linesDesigner/linesDesigner.css";
import "./components/selectionBehabiour/selectionBehabiour.css";
import "./components/toolsBarIcon/toolsBarIcon.css";
import "./components/toolsMagicWandOptions/toolsMagicWandOptions.css";
import "./components/toolsBucketOptions/toolsBucketOptions.css";
import "./components/toolsTransformOptions/toolsTransformOptions.css";
import "./components/toolsPointerOptions/toolsPointerOptions.css";
import "./components/toolsCrazyOptions/toolsCrazyOptions.css";
import "./components/toolsCropOptions/toolsCropOptions.css";
import "./components/svgExporter/svgExporter.css";
import "./components/theGlobalGoalsPicker/theGlobalGoalsPicker.css";
import "./components/eyes/eyes.css";
import "../vendor/ajsr-confirm/dist/css/tmplt-default.css";
import "../vendor/ajsr-notify/dist/css/tmplt-default.css";
import "./toolsBar.css";

window.$ = $;
window.jQuery = $;
window.BrushDesignerV2Assets = {
    "bd2-bg.png": brushDesigner2BackgroundUrl,
    "bd2-handles.png": brushDesigner2HandlesUrl,
    stylesIncluded: true
};
window.ResizeImageResamplingAlgorithms = resizeImageResamplingAlgorithms;

await import("./components/brushdesigner.v1/jqbrushdesigner.js");
await import("./components/brushdesigner.v1/brushEditorOutputs.js");
await import("./components/bigColorPicker/bigColorPicker.js");
await import("./components/appMenu/appMenu.js");
await import("./components/layersPanel/layersPanel.js");
await import("./components/foregroundBackgroundColors/foregroundBackgroundColors.js");
await import("../vendor/div-lines/dist/div-lines.min.js");
await import("./components/coordinateLabel/coordinateLabel.js");
await import("./components/boardRules/boardRules.js");
await import("./components/paintBoard/tempLayer.js");
await import("./components/paintBoard/layersManager.js");
await import("./components/paintBoard/imageTransforms/distortAlgorithms.js");
await import("./components/paintBoard/imageTransforms/scaleAlgorithms.js");
await import("./components/paintBoard/imageTransforms/affineTransformAlgorithms.js");
await import("./components/paintBoard/imageTransforms/perspectiveTransformAlgorithms.js");
await import("./components/paintBoard/imageTransforms/warpTransformAlgorithms.js");
await import("./components/paintBoard/imageTransforms/imageTransformRegistry.js");
await import("./components/paintBoard/paintBoard.js");
await import("./components/paintTools/paintTools.js");
await import("./components/simpleColorPicker/simpleColorPicker.js");
await import("./components/simpleLineWidthPicker/simpleLineWidthPicker.js");
await import("./components/simpleBrushWidthPicker/simpleBrushWidthPicker.js");
await import("./components/windowsManager/windowsManager.js");
await import("./components/modalWindow/modalWindow.js");
await import("./components/newDocumentDialog/newDocumentDialog.js");
await import("./components/resizeImage/resizeImage.js");
await import("./components/brightnessContrastDialog/brightnessContrastDialog.js");
await import("./components/multiPaste/multiPaste.js");
await import("./components/retroBrushDesigner/retroBrushDesigner.js");
await import("./components/randomLinesDesigner/randomLinesDesigner.js");
await import("./components/patternsView/patternsView.js");
await import("./components/gradientPanel/gradientPanel.js");
await import("./components/starGenerator/starGenerator.js");
await import("./components/linesDesigner/linesDesigner.js");
await import("./components/selectionBehabiour/selectionBehabiour.js");
await import("./components/toolsBarIcon/toolsBarIcon.js");
await import("./components/toolsMagicWandOptions/toolsMagicWandOptions.js");
await import("./components/toolsBucketOptions/toolsBucketOptions.js");
await import("./components/toolsTransformOptions/toolsTransformOptions.js");
await import("./components/toolsPointerOptions/toolsPointerOptions.js");
await import("./components/toolsCrazyOptions/toolsCrazyOptions.js");
await import("./components/toolsCropOptions/toolsCropOptions.js");
await import("./components/svgExporter/svgExporter.js");
await import("./components/theGlobalGoalsPicker/theGlobalGoalsPicker.js");
await import("./components/eyes/eyes.js");
await import("./components/brushdesigner.v2/brushdesigner.v2.js");
await import("../vendor/ajsr-confirm/dist/ajsr-js-confirm.min.js");
await import("../vendor/ajsr-notify/dist/ajsr-notify.min.js");
await import("./app.clipboard.js");
await import("./zoom.js");
await import("./app.openWindows.js");
await import("./filters/desaturate.js");
await import("./filters/invertColors.js");
await import("./filters/blur.js");
await import("./filters/sepia.js");
await import("./filters/solarize.js");
await import("./filters/posterize.js");
await import("./filters/emboss.js");
await import("./filters/edgeDetect.js");
await import("./filters/sharpen.js");
await import("./filters/grayscaleAvg.js");
await import("./filters/autoContrast.js");
await import("./filters/removeAlpha.js");
await import("./io/projectIo.js");
await import("./io/pdfExporter.js");
await import("./app.js");
